- name: Digital Solutions to Address COVID-19
  description: Digital Solutions for a 21st Century Pandemic
  items:
    - Overview
    - COVID-19 ChatBots
    - GoBusiness COVID Portal
    - GoWhere Suite
    - HealthCerts
    - Notarise
    - SafeEntry
    - Space Out
    - SPOTON
    - SupplyAlly
    - TraceTogether
    - Verify (Digital Certificates)
    - VigilantGantry

- name: Open-source
  description: Government-built open-source technologies and tools

- name: Analytics
  description: Web analytics tools to help you better understand your users and make data-driven decisions
  items:
    - Overview
    - Analytics.gov
    - GovText
    - Personalise
    - VAS
    - WOGAA

- name: Blockchain
  description: Distributed ledger technologies that enable the usage of decentralised, tamper-proof records
  items:
    - Overview
    - OpenAttestation
    - OpenCerts
    - TradeTrust

- name: Content Management
  description: Platforms that enable easy and reliable hosting and publishing of content on the web
  items:
    - Overview
    - Content Website Platform
    - Isomer
    
- name: Cybersecurity
  description: Platforms and tools to protect your networks, systems and applications from digital attacks
  items:
    - Overview
    - ACAS
    - Cloudscape
    - MASH
    - SEED
    - XCA

- name: Data and APIs
  description: Open APIs and platforms allowing developers to connect with data and services from the Government
  items:
    - Overview
    - APEX
    - BookingSG
    - Cloud File Transfer
    - Data.gov.sg
    - IRAS API Marketplace
    - Land Transport Datamall
    - MAS APIs
    - OneMap APIs
    - SingStat APIs
    - Tourism Information and Services Hub
    - URA APIs
    - Vault

- name: Design
  description: Design guidelines and libraries
  items:
    - Overview
    - Singapore Government Design System

- name: DevOps
  description: Tools that enable the delivery of software quickly, securely and reliably in the spirit of DevOps
  items:
    - Overview
    - Container Stack
    - SHIP-HATS
    - StackOps

- name: Digital Identity
  description: Make use of Government-backed digital identities to identify and transact with individuals and businesses
  items:
    - Overview
    - Corppass
    - Identiface
    - Login
    - Myinfo
    - Myinfo business
    - National Digital Identity
    - Notify
    - SGFinDex
    - Singpass
    - Verify

- name: Infrastructure and Hosting
  description: Host applications in secure environments at scale
  items:
    - Overview
    - Government on Commercial Cloud
    - 'I2C {{Infra to Code}}'
    - Secure Infrastructure-as-Code

- name: Sensor Platforms and Internet of Things
  description: Build on sensors and IOT technologies and leverage their data
  items:
    - Overview
    - Asynchronous Data Exchange
    - DECADA - IoT Tech Stack
    - DECADA Embedded
    - DECADA Edge Gateway
    - DECADA Cloud
    - Digital Operations Smart Services
    - eCanvas
    - ePAD
    - Lamppost-as-a-Platform
    - Open Digital Platform
    - Personal Alert Button
    - SenseOps
    - Sensor Asset Management
    - Smart Gardens
    - SmartGym
    - SNSP
    - SPOTON

- name: Platform
  description: Digital platform for citzens, agencies and businesses
  items:
    - Overview
    - GoBusiness
    - LifeSG
    - MyMoneySense
    - GovWallet
    - OurSG
    - Virtual Intelligent Chat Assistant

- name: Productivity Tools
  description: Tools to enhance your experience at work and help you achieve more
  items:
    - Overview
    - CrowdTaskSG
    - FormSG
    - GatherSG
    - Postman
    - RedeemSG
    - TechBiz
    - Transcribe
